[build]
  # Since this is a static site, no build command needed
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Handle client-side routing (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic redirects for clean URLs
[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200